# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options
language: ruby
rvm:
  - 1.9.3
  - 2.0.0

before_install:
  - gem update bundler

matrie:
  allow_failures:
    - rvm: 1.9.3
    - rvm: 2.0.0

env:
  - TZ="Asia/Tokyo"

script: bundle exec rake test
