# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options
language: ruby
rvm:
  - 2.1.*
  - 2.2.*
  - 2.3.*
gemfile:
  - Gemfile
  - Gemfile.fluentd.v0.12
  - Gemfile.fluentd.v0.10
before_install:
  - gem update bundler
env:
  - TZ="Asia/Tokyo"
script: bundle exec rake test
